% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Project Applied Biostatistics},
  pdfauthor={Santiago Anton Moreno},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{Project Applied Biostatistics}
\author{Santiago Anton Moreno}
\date{16/03/2020}

\begin{document}
\maketitle

Our goal is to find a model that describe the rate of fungal invasion of
5 varieties of apples for 7 fusarium strains.

\begin{verbatim}
##    variety strain days weight radius radial   rate
## 1        1      2   70  153.9   3.65   1.23 0.0176
## 2        1      3   70  137.8   3.51   1.25 0.0179
## 3        1      4   70  141.0   3.53   1.66 0.0237
## 4        1      5   70  145.8   3.58   1.74 0.0249
## 5        1      6   70  147.8   3.60   1.88 0.0269
## 6        1      7   70  174.9   3.81   2.26 0.0323
## 7        2      1  103   91.3   3.07   1.16 0.0113
## 8        2      2  103  115.5   3.05   1.26 0.0122
## 9        2      3  103   99.5   3.15   0.41 0.0040
## 10       2      4  103  101.2   3.17   2.39 0.0232
## 11       2      5  103  106.8   3.23   2.01 0.0195
## 12       2      6  103   88.1   3.03   1.98 0.0192
## 13       2      7  103  100.2   3.16   2.26 0.0219
## 14       3      1   54   66.5   2.66   2.29 0.0424
## 15       3      2   54   67.6   2.68   1.02 0.0189
## 16       3      3   54   64.8   2.64   0.27 0.0050
## 17       3      4   54   59.3   2.57   2.63 0.0487
## 18       3      5   54   70.1   2.71   2.58 0.0478
## 19       3      6   54   68.1   2.69   2.11 0.0391
## 20       3      7   54   64.0   2.63   2.73 0.0506
## 21       4      1  138   68.7   2.74   1.46 0.0106
## 22       4      2  138   66.7   2.71   0.53 0.0038
## 23       4      3  138   72.4   2.78   0.05 0.0004
## 24       4      4  138   68.6   2.74   1.69 0.0122
## 25       4      5  138   68.0   2.73   1.60 0.0116
## 26       4      6  138   62.2   2.65   2.15 0.0156
## 27       4      7  138   73.1   2.79   1.67 0.0121
## 28       5      1   89   62.7   2.46   1.33 0.0149
## 29       5      2   89   60.6   2.44   0.59 0.0066
## 30       5      3   89   67.8   2.53   0.60 0.0067
## 31       5      4   89   64.4   2.44   1.95 0.0219
## 32       5      5   89   54.5   2.35   1.76 0.0198
## 33       5      6   89   57.4   2.40   1.25 0.0140
## 34       5      7   89   60.9   2.44   2.05 0.0230
\end{verbatim}

Description: Rate of fungal invasion of 5 varieties of apples for 7
fusarium strains.

Varieties: 1=Bramley's Seedling, 1925-26 @12C. 70 Days 2=Bramley's
Seedling, 1924-25 @12C. 103 Days 3=Cox's Orange Pippin, 1924-25 @12C. 54
Days 4=Cox's Orange Pippin, 1924-25 @3C. 138 Days 5=Cox's Orange Pippin,
1925-26 @12C. 89 Days

Fusarium Strains: 1=A 2=B11 3=B111 4=C1 5=C21 6=C3 7=D

Variables/Columns Variety 8 Fusarium Strain 16 Days 22-24 Apple Weight
(grams) 27-32 Radius (cm) 36-40 Fungal Radial Advance (cm) 44-48 Rate of
advance (cm/day) 51-56

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#library(GGally)}
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\KeywordTok{boxplot}\NormalTok{(rate}\OperatorTok{~}\NormalTok{strain,}\DataTypeTok{data =}\NormalTok{ data)}
\KeywordTok{boxplot}\NormalTok{(radial}\OperatorTok{~}\NormalTok{variety,}\DataTypeTok{data =}\NormalTok{ data)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Markdown_project_files/figure-latex/exploratory analysis-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#ggpairs(data)}
\end{Highlighting}
\end{Shaded}

As we can see in those two plots the homoskedacity property is clearly
violated thus we should be carefull when doing analysis. The strain
factor seems to be more informative than the apple variety. Normality is
also violated as we see that the boxplot for some strains or variety are
clearly non symetric which suggest non-normality of the rate. Indepence
should be preserved since the study was done cleanly.

\#Bon, la variety 3 et 5 c'est chelou. Meme race, meme C qui est les
celsius je pense, mais variety 5 a plus de days, pourtant variety 3 au
beaucoup plus de rate. On peut meme pas expliquer par le fait que
l'expension est plus rapide au début car enfaite c'est variety 3 qui a
plus de radial à la fin. peut-être il y une erreur et il faut swap?
peut-être l'expérience est claqué au sol avec pas les mêmes conditions ?
Je pense que c'est surement que les pommes n'ont pas la même maturité.
faudra le mentionner bien et tout. Cela ``justifie'' le fait d'utiliser
variety 1,2,3,4,5 au lieu de juste séparer les différentes races de
pommes, vu que selon leur maturité(information inconnu) tout change et
en plus pour justifier pq on bosse pas avec temperature on peut dire
aussi que c'est partout la meme sauf 1.

As the rate of fungal expension and the fungal radial advance are
redundant information, we have to choose which one will we discard and
which one will we use as the response. We decided to use the rate, we
will justify it later in the notebook.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#plot.design(data) ce plot la est un peu moche peut-être faut trouver un autre moyen}
\KeywordTok{interaction.plot}\NormalTok{(data}\OperatorTok{$}\NormalTok{variety,data}\OperatorTok{$}\NormalTok{strain,data}\OperatorTok{$}\NormalTok{rate, }\DataTypeTok{col=}\KeywordTok{c}\NormalTok{(}\StringTok{'blue'}\NormalTok{,}\StringTok{'red'}\NormalTok{,}\StringTok{'violet'}\NormalTok{,}\StringTok{'green'}\NormalTok{,}\StringTok{'orange'}\NormalTok{,}\StringTok{'grey'}\NormalTok{,}\StringTok{'black'}\NormalTok{), }\DataTypeTok{lty=}\DecValTok{1}
\NormalTok{                 ,}\DataTypeTok{xlab=}\StringTok{'variety'}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{'rate of fungal invasion(cm/day)'}\NormalTok{, }\DataTypeTok{trace.label=} \StringTok{'strain'}\NormalTok{)}\CommentTok{#j'aurais pu mettre col=1:7 mais faut eviter le jaune }
\end{Highlighting}
\end{Shaded}

\includegraphics{Markdown_project_files/figure-latex/exploratory-1.pdf}
There are several things we may notice from this plot. The general rate
of fungal invasion varies a lot depending on the variety of the apple.
Also different strains induce have different rates of fungal invasion.
We see that all the lines have more or less the same shape but with
different scaling, which suggest that a model that include just strain
and variety should be decent.

We can see on this plot that there is no data point for variety 1 and
strain 1. This was suspicious, so we checked with the dataset online and
the first row of the dataset is indeed missing. So we manually reinsert
the missing value.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#A run une seule fois}
\NormalTok{data<-}\KeywordTok{rbind}\NormalTok{(data, }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{variety=}\DecValTok{1}\NormalTok{,}\DataTypeTok{strain=}\DecValTok{1}\NormalTok{,}\DataTypeTok{days=}\DecValTok{70}\NormalTok{,}\DataTypeTok{weight=}\FloatTok{156.2}\NormalTok{,}\DataTypeTok{radius=}\FloatTok{3.66}\NormalTok{,}
                             \DataTypeTok{radial=}\FloatTok{2.04}\NormalTok{,}\DataTypeTok{rate=}\FloatTok{0.0291}\NormalTok{))}
\CommentTok{#rajouté cette valeur ca a changé un peu les fits mais pas trop j'ai l'impression}
\end{Highlighting}
\end{Shaded}

Now we can try to fit our model now. We start by doing an analysis of
variance.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model.full=}\KeywordTok{aov}\NormalTok{(rate}\OperatorTok{~}\NormalTok{strain}\OperatorTok{+}\NormalTok{variety}\OperatorTok{+}\NormalTok{radius}\OperatorTok{+}\NormalTok{weight}\OperatorTok{+}\NormalTok{days,}\DataTypeTok{data=}\NormalTok{data)}
\NormalTok{step.model=}\KeywordTok{stepAIC}\NormalTok{(model.full,}\DataTypeTok{direction=}\StringTok{"backward"}\NormalTok{,}\DataTypeTok{trace=}\OtherTok{FALSE}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(step.model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             Df    Sum Sq   Mean Sq F value   Pr(>F)    
## strain       6 0.0018670 0.0003112   8.618 4.70e-05 ***
## variety      4 0.0030056 0.0007514  20.810 1.63e-07 ***
## Residuals   24 0.0008666 0.0000361                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

By looking at the p-values, we can conclude that strain and variety
variables must be included in our model. The backward elimination
suggest that weight,radius and number of days are not significant.

The fact that the number of days is insignificant also suggest than the
rate is constant in time, which justify using the rate of fungal
invasion as our response instead of the fungal radial advance.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model}\FloatTok{.1}\NormalTok{=}\KeywordTok{lm}\NormalTok{(rate}\OperatorTok{~}\NormalTok{strain}\OperatorTok{+}\NormalTok{variety,}\DataTypeTok{data=}\NormalTok{data)}
\KeywordTok{summary}\NormalTok{(model}\FloatTok{.1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = rate ~ strain + variety, data = data)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -0.0176029 -0.0020429  0.0000771  0.0032586  0.0072771 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  0.026020   0.003369   7.724 5.84e-08 ***
## strain2     -0.009840   0.003800  -2.589 0.016092 *  
## strain3     -0.014860   0.003800  -3.910 0.000661 ***
## strain4      0.004280   0.003800   1.126 0.271217    
## strain5      0.003060   0.003800   0.805 0.428622    
## strain6      0.001300   0.003800   0.342 0.735276    
## strain7      0.006320   0.003800   1.663 0.109322    
## variety2    -0.008729   0.003212  -2.718 0.012013 *  
## variety3     0.011443   0.003212   3.563 0.001578 ** 
## variety4    -0.015157   0.003212  -4.719 8.48e-05 ***
## variety5    -0.009357   0.003212  -2.913 0.007619 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.006009 on 24 degrees of freedom
## Multiple R-squared:  0.849,  Adjusted R-squared:  0.7861 
## F-statistic: 13.49 on 10 and 24 DF,  p-value: 1.403e-07
\end{verbatim}

The results from the estimates are in agreement with the interpretation
plot. For example, the estimates for the variables of strain 2 and 3
have negative values, which makes sense because in the interpretaion
plot strain 2 and strain 3 induce the lowest rates of fungal invasion.
\#faudrait trouver un moyen de faire des références a une figure

We can also look at the standart errors and p-values and conclude that
some of those variable estimates may be equal to 0. However setting them
to 0 would not change much in terms of fitting the data or change the
interpretation of the model except maybe that some strains have the same
effect on the rate. \#vérifie si je bullshit pas la. C'est un peu
inutile mais balek.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{layout}\NormalTok{(}\KeywordTok{matrix}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{,}\DataTypeTok{ncol=}\DecValTok{2}\NormalTok{))}
\KeywordTok{plot}\NormalTok{(model}\FloatTok{.1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Markdown_project_files/figure-latex/model diagnostic-1.pdf}
The row 16 is clearly an outlier. We decided to remove it along with the
row 15 (also an outlier ) because they also have too much influence in
our variable estimates. \#dire qu'ils sont trop influents ca justifie de
les enlever un peut, jsp pas pouquoi mais le cook distance plot est
remplacé par un truc chelou donc pas sure que se soit vrai, mais les
valeur en strain 3 and strain 2 et variety 3 change pas mal en enlevant
ces points

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model}\FloatTok{.2}\NormalTok{=}\KeywordTok{lm}\NormalTok{(rate}\OperatorTok{~}\NormalTok{strain}\OperatorTok{+}\NormalTok{variety,}\DataTypeTok{data=}\NormalTok{data[}\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{15}\NormalTok{,}\OperatorTok{-}\DecValTok{16}\NormalTok{),])}
\CommentTok{#summary(model.2)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{layout}\NormalTok{(}\KeywordTok{matrix}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{,}\DataTypeTok{ncol=}\DecValTok{2}\NormalTok{))}
\KeywordTok{plot}\NormalTok{(model}\FloatTok{.2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Markdown_project_files/figure-latex/model fitting4-1.pdf}
Now the different diagnostic plots suggest that the model fit the data
much better now, so we decide to use it as our final model.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model}\FloatTok{.2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = rate ~ strain + variety, data = data[c(-15, -16), 
##     ])
## 
## Coefficients:
## (Intercept)      strain2      strain3      strain4      strain5      strain6  
##    0.024704    -0.006343    -0.009143     0.004280     0.003060     0.001300  
##     strain7     variety2     variety3     variety4     variety5  
##    0.006320    -0.008729     0.018024    -0.015157    -0.009357
\end{verbatim}

There are numerous shortcomings to our model. The first one is the clear
lack of data, having only one data point per variety and strain is
cleary to low, which means any outlier greatly influence our model.

Another problem is that our model does not include any notion of
``special interaction'' between some stains and variety. For example, it
is possible some varieties of apple have more immunity against some kind
of fusarium strains than others. This might explain why we have outliers
with our model.

\#There is also the fact that maybe the expension of the radius of the
fungal invasion might not be linear. If we let the fusarium invade the
apple long enough, it's expension will necessarily stop at one point
because the apple radius is finite. We could also expect the expension
to slowdown after it reaches a certain proportion of the apple. The
expension of the radius not being linear would mean that the rate of
fungal invasion that our model try to predict is kind of useless. Cela
est ``justifié'' car days est insignifiant.

The final problem is that our model don't gives us much insight on the
fungal expension. Our model try to predict the rate of fungal expension
for a given race without taking care of the temperature or maturity of
the apple. But it doesn't tell us how this rate changes depending on the
temperature or maturity of the apple. \#bon le troisième est peut-etre
un peu forcé et faut trouver des meilleurs mots \#pour la conclusion on
demande plus de data, de la meilleur data (genre inclure température et
maturité des pommes) et peut-etre on peut tenter des modèles plus
complexes pas forcément linéaires.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#see the changes between factors}
\NormalTok{tuk<-}\KeywordTok{TukeyHSD}\NormalTok{(}\KeywordTok{aov}\NormalTok{(model}\FloatTok{.2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(tuk)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Markdown_project_files/figure-latex/diag-1.pdf}
\includegraphics{Markdown_project_files/figure-latex/diag-2.pdf}

\end{document}
